/**
 * AuditSkills — AI Generation Route (Gemini)
 * POST /api/generate/tests          — generate test procedures for a skill
 * POST /api/generate/classification — generate classification rules from tests
 */
const express = require('express');
const router  = express.Router();

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

// ── Gemini caller ─────────────────────────────────────────────────────────────
async function callGemini(prompt) {
  if (!GEMINI_API_KEY) throw new Error('GEMINI_API_KEY environment variable is not set');
  const { GoogleGenerativeAI } = require('@google/generative-ai');
  const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
  const model = genAI.getGenerativeModel({ model: 'gemini-3-flash-preview' });
  const result = await model.generateContent(prompt);
  return result.response.text();
}

/** Strip markdown code fences and parse JSON safely. */
function parseJsonFromLLM(raw) {
  const cleaned = raw
    .replace(/```json\s*/gi, '')
    .replace(/```\s*/g,      '')
    .trim();
  return JSON.parse(cleaned);
}

// ── POST /api/generate/tests ──────────────────────────────────────────────────
router.post('/tests', async (req, res) => {
  try {
    const { skill } = req.body;
    if (!skill) return res.status(400).json({ error: 'skill object required' });

    const step1  = skill.step1  || {};
    const step2  = skill.step2  || {};
    const fields = (step2.fieldMappings || [])
      .map(f => ({ name: f.logicalName || f.canonicalName, type: f.dataType || f.type }))
      .filter(f => f.name);

    const prompt = `
You are an expert internal auditor and audit automation engineer.

Given the following audit skill definition, generate a JSON array of audit test procedures that will be executed by an automated audit test engine.

## Skill Details
- Name: ${skill.name || 'Unnamed'}
- Category: ${skill.meta?.category || 'General'}
- Audit Objective: ${step1.auditObjective || ''}
- Assertions: ${(step1.assertions || []).join(', ') || 'Not specified'}
- Inherent Risk: ${step1.inherentRisk || 'High'}
- Materiality Threshold: $${step1.materialityUsd || 10000}
- Audit Period: ${step1.auditPeriod?.label || ''}
- Available Data Fields: ${fields.map(f => `${f.name} (${f.type})`).join(', ')}

## Rules for test generation
Each test object MUST follow this exact schema:
{
  "id": "T01",                       // sequential, T01–T99
  "name": "Short descriptive name",
  "type": "population_100pct" | "analytical" | "sampling",
  "objective": "One sentence explanation of what this test detects",
  "criteria": { ... }               // see below
}

### Criteria schemas by test type:

**population_100pct with null_when:**
{ "op": "null_when", "field": "<logicalName>", "condition": { "field": "<amountField>", "op": "gt", "value": <number> } }

**population_100pct with three_way_match:**
{ "type": "three_way_match", "invoiceAmountField": "<field>", "poAmountField": "<field>", "tolerancePct": 0.05 }

**population_100pct with simple comparison (gt/gte/lt/lte/eq):**
{ "op": "gt", "field": "<logicalName>", "value": <number> }

**analytical with split_payment:**
{ "type": "split_payment", "vendorField": "<field>", "amountField": "<field>", "dateField": "<field>", "amountThreshold": <number>, "windowDays": <number> }

**analytical with exact_duplicate:**
{ "type": "exact_duplicate", "keyFields": ["<field1>", "<field2>", "<field3>"] }

**sampling:**
{ "sampleSize": <number>, "selection": "top_risk", "selectionField": "<amountField>" }

## Important
- Only use field names that exist in the Available Data Fields list above
- Generate 2–5 tests appropriate to the objective and assertions
- For Completeness assertions: generate null_when or missing-field tests
- For Accuracy/Valuation: generate three_way_match or exact_duplicate tests
- For Existence (High/Critical risk): generate sampling test
- For Fraud risk indicators: generate split_payment tests
- Return ONLY a valid JSON array, no markdown, no explanation
`;

    const raw   = await callGemini(prompt);
    const tests = parseJsonFromLLM(raw);

    if (!Array.isArray(tests)) throw new Error('Gemini did not return an array');

    // Tag each test as AI-generated
    tests.forEach(t => { t._autoGenerated = true; t._source = 'gemini'; });

    res.json({ tests, source: 'gemini' });
  } catch (err) {
    console.error('[generate/tests] Gemini error:', err.message);
    res.status(500).json({ error: err.message, source: 'gemini' });
  }
});

// ── POST /api/generate/classification ────────────────────────────────────────
router.post('/classification', async (req, res) => {
  try {
    const { skill } = req.body;
    if (!skill) return res.status(400).json({ error: 'skill object required' });

    const step1 = skill.step1 || {};
    const tests = (skill.step3 && skill.step3.tests) || [];

    const prompt = `
You are an expert internal auditor.

Given the following audit skill and its test procedures, generate a JSON array of finding classification rules — one rule per test.

## Skill
- Name: ${skill.name || 'Unnamed'}
- Inherent Risk: ${step1.inherentRisk || 'High'}
- Materiality: $${step1.materialityUsd || 10000}
- Category: ${skill.meta?.category || ''}

## Tests
${tests.map(t => `- ${t.id}: ${t.name} (${t.type}) — ${t.objective || ''}`).join('\n')}

## Classification rule schema (one per test):
{
  "testId": "T01",
  "findingTitle": "Clear, concise finding title (50 chars max)",
  "defaultRisk": "High" | "Medium" | "Low",
  "riskLevel": "High" | "Medium" | "Low",     // same as defaultRisk
  "category": "Control Deficiency" | "Process Gap" | "Fraud Indicator" | "Compliance Issue" | "Data Quality",
  "followUp": true | false,
  "escalation": [                              // optional — escalate risk when amount exceeds threshold
    { "ifAmountGt": <number>, "thenRisk": "High" }
  ]
}

## Risk assignment guidelines
- population_100pct tests: match inherent risk (High→High, Moderate→Medium, Low→Low)
- analytical / split_payment / exact_duplicate: always High (fraud indicators)
- sampling tests: one level below inherent risk
- Add escalation rule at 5× materiality for Medium default risks
- followUp: true for High and Medium, false for Low

Return ONLY a valid JSON array of classification rules, no markdown.
`;

    const raw   = await callGemini(prompt);
    const rules = parseJsonFromLLM(raw);
    if (!Array.isArray(rules)) throw new Error('Gemini did not return an array');

    rules.forEach(r => { r._autoGenerated = true; r._source = 'gemini'; });

    // Also generate follow-up policy and recommended actions
    const hiRisk = step1.inherentRisk === 'High' || step1.inherentRisk === 'Critical';
    const followUpPolicy = {
      high:   { responseDueDays: hiRisk ? 10 : 15 },
      medium: { responseDueDays: 30 },
      low:    { responseDueDays: 60 },
    };
    const recommendedActions = {
      High:   `Immediate escalation to senior management and Audit Committee required. Root-cause analysis to be completed within 5 business days. ${hiRisk ? 'Given the elevated inherent risk, consider whether external referral is warranted if fraud is confirmed.' : ''}`,
      Medium: `Process owner to provide a written management response within 30 days. Internal audit will validate remediation in the next scheduled review cycle.`,
      Low:    `Process owner to acknowledge the observation and document a corrective action plan by the next audit cycle.`,
    };

    res.json({ rules, followUpPolicy, recommendedActions, source: 'gemini' });
  } catch (err) {
    console.error('[generate/classification] Gemini error:', err.message);
    res.status(500).json({ error: err.message, source: 'gemini' });
  }
});

module.exports = router;
